spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialmedia_db
    #url: jdbc:postgresql://postgresql_db/smartcart_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      file-size-threshold: 5MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 день
      refresh-token:
        expiration: 604800000 # 7 дней